### ISSUE TITLE
hook actionValidateOrder?

### ISSUE THREAD

**Issue by drzraf** [keupsonite/salesforce#1]
Hi, thanks for the module!
Please, let me ask here one question about the implementation:
What kept you from implementing `initFromContext()` as a hook, more specifically the `actionValidateOrder` hook?

AFAICT, _payment Modules_'s `controllers/front/validation.php` extend `ModuleFrontController` (`classes/PaymentModule.php`).
There `validateOrder()` clearly calls the `actionValidateOrder` hook (line 649)

If possible that would allow for a patch-less installation.
If not possible, it may be worth referencing the PS blocking issue(s) (about a new hook in `validateOrder()`?) from the PS bugtracker.

About the _Paybox_/_Paypal_ return code, could we assume that this variable is useful for other modules consumption and should thus be passed to `validateOrder()` (maybe via `$extra_vars`?)?
Then to the Hook call should probably be modified to pass these return code.
I don't know if these modules have their bugtrackers too to post/reference issues from.

Note: in `README.md` a `.php` is missing after _file `controllers/front/validation`_
Note: the repository would be far easier to work with if it could be directly clonable inside `prestashop/modules` (ie: move all files currently below `modules/salesforce` at the root of the repository)

thank you
(L214/Raph)

**Comment by zakarialounes** [comment]
Hi Raph and thank you for feedback!

I confirm when you are in the `actionValidateOrder` (hook), you can't know the _Paybox/Paypal_ return code, this is why i've decided to put the function call `initFromContext` in each `validation.php` file of modules. 

Is a good suggestion to put the return code in the `validateOrder`, maybe via `$extra_vars`. I keep you in touch if that is possible or not. If this is possible, we will have just to configure the parent class for all payment modules! It will be amazing!

We have only a private bugtrackers, because the source code of the payment modules is not public.

Thank for mistake in `README.md` and for the suggestion for the structure of this repository, i'll fix that soon.

**Comment by zakarialounes** [comment]
Hi,

I've found a new hook named `actionPaymentConfirmation` and i've put the function call `initFromContext` inside. Now the module works without configurations! I'll find a solution for the return code of  `paybox/paypal` soon.

**Comment by drzraf** [comment]
I tried and it seems to work so far.
Not having to patch modules anymore is unvaluable !
many thanks
